### ISSUE TITLE
Not log failed loggin attempts.

### ISSUE THREAD

**Issue by Franck2A** [splitbrain/dokuwiki-plugin-loglog#36] opened 2018-05-24 14:08 UTC
Hello,
I'm on Greebo for two dokuwiki instances, the first use auth-ldap plugin and the second one use auth-plain plugin.
For both, i don't see failed loggin attempts in /data/cache/loglog.log .
I may have missed some things ?
Tnx for help and best regards.
Franck

**Comment by oschuett** [comment] 2018-07-31 20:00
I'm having the same problem.

**Comment by wollet42** [comment] 2018-12-16 19:59
I see the same, any update on this?

All logins are logged but not the failed logins.

Thanks

**Comment by FinishedFragment** [comment] 2019-05-25 06:54
+1 for this. it is an essential security feature.

**Comment by moisesbr-dw** [comment] 2020-06-05 20:26
Of course I support this ;-)

@splitbrain please merge my pull request. It's 3 years old already...

**Comment by splitbrain** [comment] 2020-06-08 07:00
duplicate of #31

**Closed by splitbrain** 2020-06-08 07:00 UTC
